jobs:
  build:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run: go version
      - run: go mod download github.com/yuin/goldmark
      - run: go test ./... -coverprofile coverage.out
      - run: bash <(curl -s https://codecov.io/bash)
